#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Wave 1 grid-search script (auto-generated by assistant).

Searches for a SINGLE logical entry condition that achieves high Sharpe ratio and >2500 trades.
The search covers simple indicator rules such as:
    • Price > / < SMA(n)
    • Price > / < EMA(n)
    • RSI(n) < thresh or RSI(n) > thresh
    • Bollinger band breaches (close < lower or close > upper)

The universe is daily QQQ since 2006-01-01 (same preprocessing as base script.py).
Return metric: overnight return (close T -> open T+1). Signal evaluated on close T using info up to that moment (no look-ahead).

The script prints the top-N rules and appends them to history.log.
Runtime limited by outer wrapper via `timeout 180s python test_wave1.py`.
"""

import os
import sys
import itertools
from datetime import datetime
from typing import List, Tuple, Dict, Callable

import numpy as np
import pandas as pd

# -------------- CONFIG -------------------------------------------------------------------------
INPUT_FILE = os.environ.get("QQQ_CSV", "4 - QQQ.csv")
DATE_START = "2006-01-01"
ANNUAL_RF = 0.02
DAILY_RF = ANNUAL_RF / 252

# Parameter grids (<= 1000 combos)
SMA_PERIODS = list(range(5, 55, 5))             # 10
EMA_PERIODS = list(range(5, 55, 5))             # 10
RSI_PERIODS = list(range(5, 55, 5))             # 10
RSI_THRESH_LOW = [20, 25, 30, 35, 40]           # 5
RSI_THRESH_HIGH = [60, 65, 70, 75, 80]          # 5
BOLL_PERIODS = list(range(10, 55, 10))          # 5
BOLL_STD = [1.5, 2.0, 2.5]                      # 3
TOP_N = 10

# -------------- DATA LOADING -------------------------------------------------------------------

def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df.columns = df.columns.str.lower()
    df.rename(columns={"date": "date"}, inplace=True)
    df["date"] = pd.to_datetime(df["date"])
    df = df[df["date"] >= DATE_START].copy()
    # compute next open and overnight return
    df["next_open"] = df["open"].shift(-1)
    df["next_ov_return"] = df["next_open"] / df["close"] - 1
    return df.dropna().reset_index(drop=True)

qqq = load_data(INPUT_FILE)
close = qqq["close"]

# -------------- INDICATOR HELPERS ---------------------------------------------------------------

def sma(series: pd.Series, n: int) -> pd.Series:
    return series.rolling(window=n).mean()

def ema(series: pd.Series, n: int) -> pd.Series:
    return series.ewm(span=n, adjust=False).mean()

def rsi(series: pd.Series, n: int) -> pd.Series:
    delta = series.diff()
    up = np.where(delta > 0, delta, 0.0)
    down = np.where(delta < 0, -delta, 0.0)
    roll_up = pd.Series(up).rolling(window=n).mean()
    roll_down = pd.Series(down).rolling(window=n).mean()
    rs = roll_up / roll_down
    rsi_val = 100.0 - 100.0 / (1.0 + rs)
    return pd.Series(rsi_val, index=series.index)

def bollinger(series: pd.Series, n: int, n_std: float) -> Tuple[pd.Series, pd.Series]:
    sma_ = sma(series, n)
    std_ = series.rolling(window=n).std()
    upper = sma_ + n_std * std_
    lower = sma_ - n_std * std_
    return upper, lower

# -------------- RULE GENERATORS -----------------------------------------------------------------

RuleFunc = Callable[[pd.DataFrame], pd.Series]

rule_candidates: List[Tuple[str, RuleFunc]] = []

# SMA rules
for n in SMA_PERIODS:
    rule_candidates.append((f"close_gt_sma{n}", lambda df, n=n: (df["close"] > sma(df["close"], n))))
    rule_candidates.append((f"close_lt_sma{n}", lambda df, n=n: (df["close"] < sma(df["close"], n))))

# EMA rules
for n in EMA_PERIODS:
    rule_candidates.append((f"close_gt_ema{n}", lambda df, n=n: (df["close"] > ema(df["close"], n))))
    rule_candidates.append((f"close_lt_ema{n}", lambda df, n=n: (df["close"] < ema(df["close"], n))))

# RSI low/high rules
for n in RSI_PERIODS:
    rsi_series = rsi(close, n)
    for thr in RSI_THRESH_LOW:
        rule_candidates.append((f"rsi{n}_lt_{thr}", lambda df, n=n, thr=thr, series=rsi_series: (series < thr)))
    for thr in RSI_THRESH_HIGH:
        rule_candidates.append((f"rsi{n}_gt_{thr}", lambda df, n=n, thr=thr, series=rsi_series: (series > thr)))

# Bollinger band breaches
for n in BOLL_PERIODS:
    for dev in BOLL_STD:
        upper_, lower_ = bollinger(close, n, dev)
        rule_candidates.append((f"close_lt_lowerBB_{n}_{dev}", lambda df, l=lower_: (df["close"] < l)))
        rule_candidates.append((f"close_gt_upperBB_{n}_{dev}", lambda df, u=upper_: (df["close"] > u)))

# Limit to <= 1000 rules
rule_candidates = rule_candidates[:1000]

# -------------- EVALUATION ----------------------------------------------------------------------

def evaluate_signal(signal: pd.Series, ov_ret: pd.Series) -> Tuple[float, int]:
    """Return Sharpe ratio and trade count."""
    strategy_return = signal.shift(0) * ov_ret  # open at close T, exit at open T+1 uses same-day signal
    strategy_return = strategy_return.dropna()
    excess = strategy_return - DAILY_RF
    mean_excess_annual = excess.mean() * 252
    std_excess_annual = excess.std() * np.sqrt(252)
    sharpe = mean_excess_annual / std_excess_annual if std_excess_annual > 0 else 0.0
    trades = int(signal.sum())
    return sharpe, trades

results: List[Tuple[str, float, int]] = []

for name, func in rule_candidates:
    sig = func(qqq).astype(int)
    sharpe, trades = evaluate_signal(sig, qqq["next_ov_return"])
    results.append((name, sharpe, trades))

# sort by sharpe desc
results.sort(key=lambda x: x[1], reverse=True)

print("Top results (Wave 1):")
for idx, (cond, sh, tr) in enumerate(results[:TOP_N], start=1):
    print(f"{idx:2d}. {cond:30s} | Sharpe: {sh:6.3f} | Trades: {tr}")

# save top 3 to history.log
hist_lines = []
now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
for cond, sh, tr in results[:3]:
    hist_lines.append(f"[{now}] Wave1 | {cond} | Sharpe={sh:.3f} | Trades={tr}\n")

with open("history.log", "a", encoding="utf-8") as fh:
    fh.writelines(hist_lines)

print("\nTop 3 appended to history.log")